### ISSUE TITLE
Negative loss and Dice/FScore more than 1

### ISSUE THREAD

**Issue by MrOCW** [dhassault/tf-semantic-example#1]
Hi @dhassault ,

I am implementing a binary semantic segmentation and during training, the F1 score is more than 1 and the loss is negative. Any idea why this might be the case?
My model input dimensions are 256 256 3 and output dimensions are 256 256 1

These are the functions for the metric and loss:

def dice_coefficient(y_true,y_pred, smooth = 1e-07):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true*y_pred)
    return (2.*intersection+smooth)/(K.sum(y_true_f)+K.sum(y_pred_f)+smooth)

def dice_coefficient_loss(y_true, y_pred):
    return 1-dice_coefficient(y_true, y_pred)

**Comment by dhassault** [comment]
Hi Ong Chee Wei ! 
Thank you a lot for comment :) 

There is a square missing. Try this:

```python
def dice_coefficient(y_true,y_pred, smooth = 1e-07):
   y_true_f = K.flatten(y_true)
   y_pred_f = K.flatten(y_pred)
   intersection = K.sum(y_true*y_pred)
   return (2.*intersection+smooth)/(K.sum(K.square(y_true_f),-1)+K.sum(K.square(y_pred_f),-1)+smooth)

def dice_coefficient_loss(y_true, y_pred):
   return 1-dice_coefficient(y_true, y_pred)
```
ref: https://arxiv.org/pdf/1606.04797v1.pdf
